// Merges data/foods/*.json + data/sources.json into one bundled ES module the app
// imports directly (no fetch → works offline, on file://, and inside the service worker cache).
//
// Source of truth stays data/foods/*.json. Run after ANY data edit:
//   node scripts/validate-data.mjs && node scripts/build-data.mjs
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const foodsDir = join(root, "data", "foods");
const outDir = join(root, "assets", "data");
const outFile = join(outDir, "foods.js");

const foods = [];
const seen = new Set();

for (const file of readdirSync(foodsDir).filter(f => f.endsWith(".json")).sort()) {
  const batch = JSON.parse(readFileSync(join(foodsDir, file), "utf8"));
  for (const food of batch) {
    if (seen.has(food.id)) {
      console.error(`FATAL: duplicate id "${food.id}" (${file})`);
      process.exit(1);
    }
    seen.add(food.id);
    foods.push(food);
  }
}

// Stable order so the generated file diffs cleanly between builds.
foods.sort((a, b) => a.id.localeCompare(b.id));

const sources = JSON.parse(readFileSync(join(root, "data", "sources.json"), "utf8"));
const preparations = JSON.parse(readFileSync(join(root, "data", "preparations.json"), "utf8"));

const meta = {
  count: foods.length,
  categories: foods.reduce((acc, f) => ((acc[f.category] = (acc[f.category] ?? 0) + 1), acc), {}),
  aliases: foods.reduce((n, f) => n + f.aliases.length, 0),
};

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  [
    "// GENERATED by scripts/build-data.mjs — do not edit by hand.",
    "// Source of truth: data/foods/*.json + data/sources.json",
    `export const META = ${JSON.stringify(meta)};`,
    `export const SOURCES = ${JSON.stringify(sources)};`,
    `export const PREPARATIONS = ${JSON.stringify(preparations)};`,
    `export const FOODS = ${JSON.stringify(foods)};`,
    "",
  ].join("\n"),
);

const kb = (Buffer.byteLength(readFileSync(outFile)) / 1024).toFixed(1);
console.log(`Built assets/data/foods.js — ${meta.count} foods, ${meta.aliases} aliases, ${kb} KB`);
console.log("By category:", meta.categories);
